# Generated by Django 2.2 on 2019-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRG_STUDENT_SITE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.IntegerField()),
                ('PRG', models.CharField(max_length=120)),
                ('ANNE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
            ],
        ),
    ]
