# Generated by Django 2.2.1 on 2019-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADR_STUDENTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADR_CP', models.IntegerField()),
                ('ADR_VILLE', models.CharField(max_length=120)),
                ('ADR_PAYS', models.CharField(max_length=2)),
                ('ID_ANO', models.IntegerField()),
                ('idCSV', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ADR_STUDENTS',
            },
        ),
        migrations.CreateModel(
            name='mergedTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.CharField(max_length=120)),
                ('PRG', models.CharField(max_length=120)),
                ('ANNEE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
                ('ADR_CP', models.CharField(max_length=120)),
                ('ADR_VILLE', models.CharField(max_length=120)),
                ('ADR_PAYS', models.CharField(max_length=120)),
                ('ANNEE', models.CharField(max_length=120)),
                ('ENTREPRISE', models.CharField(max_length=120)),
                ('CODE_POSTAL', models.CharField(max_length=120)),
                ('VILLE', models.CharField(max_length=120)),
                ('PAYS', models.CharField(max_length=120)),
                ('SUJET', models.CharField(max_length=120)),
                ('REMUNERATION', models.CharField(max_length=120)),
                ('idCSV', models.IntegerField(blank=True, null=True)),
                ('idCSVDescript', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'mergedtables',
            },
        ),
        migrations.CreateModel(
            name='PRG_STUDENT_SITE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.IntegerField()),
                ('PRG', models.CharField(max_length=120)),
                ('ANNE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
                ('idCSV', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PRG_STUDENT_SITE',
            },
        ),
        migrations.CreateModel(
            name='STUDENT_INTERNSHIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANNEE', models.CharField(max_length=120)),
                ('ANNEE_SCOLAIRE', models.CharField(max_length=120)),
                ('ENTREPRISE', models.CharField(max_length=120)),
                ('CODE_POSTAL', models.CharField(max_length=120)),
                ('VILLE', models.CharField(max_length=120)),
                ('PAYS', models.CharField(max_length=120)),
                ('SUJET', models.CharField(max_length=120)),
                ('REMUNERATION', models.FloatField()),
                ('ID_ANO', models.IntegerField()),
                ('idCSV', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'STUDENT_INTERNSHIP',
            },
        ),
    ]
