# Generated by Django 2.2 on 2019-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prg_student_site',
            name='idCSV',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
