# Generated by Django 2.2 on 2019-05-14 19:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mergedTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.CharField(max_length=120)),
                ('PRG', models.CharField(max_length=120)),
                ('ANNEE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
                ('ADR_CP', models.IntegerField()),
                ('ADR_VILLE', models.CharField(max_length=120)),
                ('ADR_PAYS', models.CharField(max_length=120)),
                ('ANNEE', models.CharField(max_length=120)),
                ('ENTREPRISE', models.CharField(max_length=120)),
                ('CODE_POSTAL', models.IntegerField()),
                ('VILLE', models.CharField(max_length=120)),
                ('PAYS', models.CharField(max_length=120)),
                ('SUJET', models.CharField(max_length=120)),
                ('REMUNERATION', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'mergedtables',
            },
        ),
        migrations.AlterModelManagers(
            name='adr_students',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='prg_student_site',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student_internship',
            managers=[
                ('pdobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='student_internship',
            old_name='ENTERPRISE',
            new_name='ENTREPRISE',
        ),
    ]
