# Generated by Django 2.2 on 2019-05-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0002_auto_20190514_2146'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='prg_student_site',
            managers=[
            ],
        ),
    ]
