# Generated by Django 2.2 on 2019-05-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0003_auto_20190514_2210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adr_students',
            managers=[
            ],
        ),
    ]
