# Generated by Django 2.2 on 2019-05-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataCRUD', '0004_auto_20190515_0643'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_internship',
            managers=[
            ],
        ),
    ]
