# Generated by Django 2.2 on 2019-05-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mergedTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.CharField(max_length=120)),
                ('PRG', models.CharField(max_length=120)),
                ('ANNEE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
                ('ADR_CP', models.IntegerField()),
                ('ADR_VILLE', models.CharField(max_length=120)),
                ('ADR_PAYS', models.CharField(max_length=120)),
                ('ANNEE', models.CharField(max_length=120)),
                ('ENTREPRISE', models.CharField(max_length=120)),
                ('CODE_POSTAL', models.IntegerField()),
                ('VILLE', models.CharField(max_length=120)),
                ('PAYS', models.CharField(max_length=120)),
                ('SUJET', models.CharField(max_length=120)),
                ('REMUNERATION', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'mergedtables',
            },
        ),
        migrations.CreateModel(
            name='ProgramTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_ANO', models.IntegerField()),
                ('PRG', models.CharField(max_length=120)),
                ('ANNE_SCOLAIRE', models.CharField(max_length=120)),
                ('SITE', models.CharField(max_length=120)),
            ],
        ),
    ]
