# Generated by Django 2.2 on 2019-05-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mergedTables',
        ),
        migrations.DeleteModel(
            name='ProgramTable',
        ),
    ]
